import turtle as t
def logo():
    t.begin_fill()
    t.circle(200,90)
    t.right(270)
    t.circle(200,90)
    t.end_fill()
logo()
t.penup()
t.goto(-20,0)
t.pendown()
t.seth(45)
logo()
t.penup()
t.goto(-40,0)
t.pendown()
t.seth(90)
logo()
t.color("white")
t.pensize(10)
def design(x,y):
    t.penup()
    t.goto(x,y) 
    t.pendown()
    t.forward(400)
design(-220,110)
design(-220,75)
design(-220,40)
t.pencolor("white")
t.goto(-150,-150)
t.down()
t.pencolor("black")
t.write("adidas", font = ("ariel",25,"bold"))
t.done()   